# syntax=docker/dockerfile:1.6
ARG ROS_DISTRO=humble
FROM --platform=$TARGETPLATFORM ros:${ROS_DISTRO}-ros-base

ARG TARGETPLATFORM
ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Update & install ROS/colcon build tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    python3-colcon-common-extensions \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \  
    ros-${ROS_DISTRO}-mavros \  
    && rm -rf /var/lib/apt/lists/*  
  
# Install GeographicLib datasets (required)  
RUN apt-get update && apt-get install -y wget \  
    && wget https://raw.githubusercontent.com/mavlink/mavros/ros2/mavros/scripts/install_geographiclib_datasets.sh \  
    && chmod +x install_geographiclib_datasets.sh \  
    && ./install_geographiclib_datasets.sh \  
    && rm install_geographiclib_datasets.sh \  
    && rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-rmw-zenoh-cpp \
 && rm -rf /var/lib/apt/lists/*

 
RUN apt-get update && apt-get install -y --no-install-recommends \
    iputils-ping \
    iproute2 \
    ros-humble-demo-nodes-cpp \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app