# syntax=docker/dockerfile:1.6
ARG ROS_DISTRO=humble
FROM --platform=$TARGETPLATFORM ros:${ROS_DISTRO}-ros-base

ARG TARGETPLATFORM
ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Update & install ROS/colcon build tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    python3-colcon-common-extensions \
    && rm -rf /var/lib/apt/lists/*



WORKDIR /app