FROM eclipse/zenoh-bridge-ros2dds:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    libnss-mdns avahi-utils \
 && rm -rf /var/lib/apt/lists/*

# Ensure glibc uses mDNS for .local
RUN sed -i 's/^hosts:.*/hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4/' /etc/nsswitch.conf || true
