# docker-compose.yml
services:
  vision:
    build:
      context: .
      dockerfile: ../docker/dockerfile.vision
    network_mode: host
    privileged: true
    ipc: host
    tty: true
    stdin_open: true
    
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video0:/dev/video0
      - /dev/video10:/dev/video10
    
    volumes:
      - /run/udev:/run/udev:ro
      - ./workspaces/vision_ws:/ros2_ws:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:ro
    
    command: >
      bash -lc "
        set -euo pipefail

        source /opt/ros/humble/setup.bash
        cd /ros2_ws || exit 1

        colcon build --symlink-install || true
        source install/setup.bash || true

        ros2 daemon start || true

        # Test caméra (optionnel)
        libcamera-hello --timeout 0 &

        # Lance ton node camera_pub
        ros2 run camera_pub camera_publisher &

        tail -f /dev/null
      "
    
    environment:
      - ROS_DOMAIN_ID=1
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - LIBCAMERA_LOG_LEVELS=*:DEBUG
    restart: unless-stopped
