# docker-compose.yml
services:
  vision:
    build:
      context: .
      dockerfile: ../docker/dockerfile.vision
    network_mode: host
    privileged: true
    ipc: host
    tty: true
    stdin_open: true
    
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video0:/dev/video0
      - /dev/video10:/dev/video10
    
    volumes:
      - /run/udev:/run/udev:ro
      - ../workspaces/vision_ws:/ros2_ws:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:ro
    
    command: >
      bash -lc "
        set -euo pipefail

        export AMENT_TRACE_SETUP_FILES=${AMENT_TRACE_SETUP_FILES:-}
        export AMENT_PYTHON_EXECUTABLE=${AMENT_PYTHON_EXECUTABLE:-$(which python3)}
        export COLCON_PREFIX_PATH=${COLCON_PREFIX_PATH:-}

        source /opt/ros/humble/setup.bash
        cd /ros2_ws || exit 1

        colcon build --symlink-install || true

        set +u
        source install/local_setup.bash 2>/dev/null || true
        source install/setup.bash 2>/dev/null || true
        set -u

        ros2 daemon start || true
        ros2 run camera_pub camera_publisher &

        tail -f /dev/null
      "
    
    environment:
      - ROS_DOMAIN_ID=1
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - LIBCAMERA_LOG_LEVELS=*:DEBUG
    restart: unless-stopped
