services:
  water:
    build:
      context: ..
      dockerfile: docker/dockerfile.water
    container_name: aeac-water
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - ../workspaces/water_ws:/water_ws
      - ../packages/bringup:/water_ws/src/bringup
      - ../packages/nav_stack:/water_ws/src/nav_stack
      - ../packages/polar_system:/water_ws/src/polar_system
      - ../packages/tools:/water_ws/src/tools
      - ../packages/vision:/water_ws/src/vision
      - ../packages/custom_interfaces:/water_ws/src/custom_interfaces
    working_dir: /water_ws     # set WS in .env, e.g. workspaces/water_ws
    command: ["bash","-lc","while :; do sleep 86400; done"]
    environment:  
      - ROS_DOMAIN_ID=2
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST

  zed-ros2:    
    image: zed_ros2_l4t_36.4.0_sdk_5.1.0:latest  
    runtime: nvidia    
    privileged: true    
    network_mode: host    
    ipc: host    
    pid: host 
    tty: true
    stdin_open: true   
    environment:    
      - NVIDIA_DRIVER_CAPABILITIES=all    
      - DISPLAY=${DISPLAY}   
      - ROS_DOMAIN_ID=2 
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST 
    volumes:    
      - /tmp/.X11-unix/:/tmp/.X11-unix    
      - /dev:/dev    
      - /dev/shm:/dev/shm    
      - /usr/local/zed/resources/:/usr/local/zed/resources/    
      - /usr/local/zed/settings/:/usr/local/zed/settings/    
      - ../config:/root/ros2_ws/config 
      - ../models:/root/ros2_ws/models 
    command: ["bash", "-lc", "source /root/ros2_ws/install/setup.bash && sleep infinity"]

  zenoh-bridge-air:  
    image: eclipse/zenoh-bridge-ros2dds:latest  
    network_mode: host  
    volumes:  
      - ../config/zenoh-air-config.json5:/config.json5:ro  
    command: ["-c", "/config.json5"]  
    environment:  
      - ROS_DOMAIN_ID=2  
      - RUST_LOG=debug
      - ROS_DISTRO=humble