services:
  zed-ros2:    
    image: zed_ros2_l4t_35.4.1_sdk_5.1.0   
    runtime: nvidia    
    privileged: true    
    network_mode: host    
    ipc: host    
    pid: host 
    tty: true
    stdin_open: true   
    environment:    
      - NVIDIA_DRIVER_CAPABILITIES=all    
      - DISPLAY=${DISPLAY}   
      - ROS_DOMAIN_ID=2 
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:    
      - /tmp/.X11-unix/:/tmp/.X11-unix    
      - /dev:/dev    
      - /dev/shm:/dev/shm    
      - /usr/local/zed/resources/:/usr/local/zed/resources/    
      - /usr/local/zed/settings/:/usr/local/zed/settings/    
      - ../config:/root/ros2_ws/config  
      - ../models:/root/ros2_ws/models  
    command: ["bash", "-lc", "sleep infinity"]
    #launch zed with :
    #ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zed2i ros_params_override_path:=config/zenith_stereo.yaml
    