services:
  zenoh-bridge-ground:  
    image: eclipse/zenoh-bridge-ros2dds:latest  
    network_mode: host  
    volumes:  
      - ../config/zenoh-ground-config.json5:/config.json5:ro  
    command: ["-c", "/config.json5"]  
    environment:  
      - ROS_DOMAIN_ID=3
      - RUST_LOG=debug
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST  